repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
      -  id: check-yaml
      -  id: end-of-file-fixer
      -  id: trailing-whitespace
      -  id: check-toml
      -  id: requirements-txt-fixer
  -   repo: https://github.com/asottile/add-trailing-comma
      rev: v3.2.0
      hooks:
      -  id: add-trailing-comma
