[project]
name = "pub-data-app-stocks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
package-mode = false
dependencies = [
    "streamlit>=1.49.1",
    "yfinance>=0.2.65",
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
]
